stroll/urls.py
from django.urls import path
from stroll import views

app_name = 'stroll'

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('signup/', views.signup, name='signup'),
    path('create-walk/', views.create_walk, name='create_walk'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('my-profile/', views.my_profile, name='my_profile'),
    path('my-profile/edit-profile/', views.edit_profile, name='edit_profile'),
    path('my-profile/my-walks/', views.my_walks, name='my_walks'),
    path('my-profile/my-questions/', views.my_questions, name='my_questions'),
    path('search-walks/', views.search_walks, name='search_walks'),
    path('walk/<str:id>/', views.show_walk, name='show_walk'),
    path('questions/', views.questions, name='questions'),
    path('questions/<int:id>', views.show_question, name='show_question'),
    path('like_walk/', views.LikeWalkView.as_view(), name='like_walk'),
    path('like_question/', views.LikeQuestionView.as_view(), name='like_question'),
    path('delete_walk/', views.DeleteWalkView.as_view(), name='delete_walk'),
    path('delete_question/', views.DeleteQuestionView.as_view(), name='delete_question'),
    path('delete_question_comment/', views.DeleteQuestionCommentView.as_view(), name='delete_question_comment'),
    path('delete_walk_comment/', views.DeleteWalkCommentView.as_view(), name='delete_walk_comment'),
]

stroll_group_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from stroll import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('stroll/', include('stroll.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stroll/forms.py
from django import forms
from django.contrib.auth.models import User
from stroll.models import *

class CreateWalkForm(forms.ModelForm):
    title = forms.CharField(max_length=30, help_text="Title:")
    area = forms.CharField(max_length=30, help_text="Area:")
    description = forms.CharField(max_length=1000, help_text="Description:")
    length = forms.IntegerField(min_value=0)
    difficulty = forms.IntegerField(min_value=0, max_value=10, help_text="Difficulty:")
    tags = forms.CharField(max_length=255, help_text="Tags:")
    thumbnail = forms.ImageField(widget=forms.FileInput(), help_text="Thumbnail", required=False)
    gallery_image_1 = forms.ImageField(widget=forms.FileInput(), help_text="Photo:", required=False)
    gallery_image_2 = forms.ImageField(widget=forms.FileInput(), help_text="Photo:", required=False)
    gallery_image_3 = forms.ImageField(widget=forms.FileInput(), help_text="Photo:", required=False)
    gallery_image_4 = forms.ImageField(widget=forms.FileInput(), help_text="Photo:", required=False)
    map_coordinates = forms.CharField(max_length=5000)

    class Meta:
        model = Walk
        fields = ('title', 'area', 'description', 'length','difficulty','tags','thumbnail','gallery_image_1','gallery_image_2','gallery_image_3','gallery_image_4','map_coordinates')
    
    def __init__(self, *args, **kwargs):
        super(CreateWalkForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.EmailField(widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'email')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

class UserProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.DateInput(), required=False)
    profile_picture = forms.ImageField(widget=forms.FileInput(), help_text="", required=False)

    class Meta:
        model = UserProfile
        fields = ('profile_picture', 'description', 'date_of_birth')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

class QuestionForm(forms.ModelForm):
    question = forms.CharField(max_length=100)

    class Meta:
        model = Question
        fields = ('question',)
    
    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

class QuestionCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=300)

    class Meta:
        model = QuestionComment
        fields = ('comment',)
    
    def __init__(self, *args, **kwargs):
        super(QuestionCommentForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

class WalkCommentForm(forms.ModelForm):
    comment = forms.CharField(max_length=300)

    class Meta:
        model = WalkComment
        fields = ('comment',)
    
    def __init__(self, *args, **kwargs):
        super(WalkCommentForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

class SearchWalkForm(forms.Form):
    pass

stroll/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views import View
from django.utils.decorators import method_decorator

from stroll.forms import *
from stroll.models import *

def home(request):
    context_dict = {}
    context_dict["popular_walks"] = Walk.objects.order_by('-likes')[:3]

    return render(request, 'stroll/home.html', context=context_dict)

def about(request):
    context_dict = {}
    context_dict["popular_walks"] = Walk.objects.order_by('-likes')[:3]
    return render(request, 'stroll/about.html', context=context_dict)

def signup(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_picture' in request.FILES:
                profile.profile_picture = request.FILES['profile_picture']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    return render(request, 'stroll/signup.html', context = {'user_form': user_form,
                                                            'profile_form':profile_form,
                                                             'registered': registered,})

@login_required
def create_walk(request):
    form = CreateWalkForm()
    if request.method == 'POST':
        form = CreateWalkForm(request.POST, request.FILES)
        request.POST.get('map_coordinates')
        request.POST.get('length')
        
        if form.is_valid():
            new_walk = form.save(commit=False)
            new_walk.user = request.user

            if 'thumbnail' in request.FILES:
                new_walk.thumbnail = request.FILES['thumbnail']

            new_walk.save()

            return redirect('/stroll/')
        else:
            print(form.errors)
    
    return render(request, 'stroll/create_walk.html', {'form':form})

def user_login(request):
    context_dict = {}

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('stroll:home'))
            else:
                return HttpResponse("Your Stroll account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            context_dict['errors'] = f"Invalid login details: {username}, {password}"
        
    return render(request, 'stroll/login.html', context=context_dict)

@login_required
def user_logout(request):
    logout(request)

    return redirect(reverse('stroll:home'))

@login_required
def my_profile(request):
    user = request.user

    if user.is_superuser:
        context_dict = {}
        context_dict['username'] = user.username + ' (superuser)'

    else:

        try:
            current_user_profile = UserProfile.objects.get(user=user)
        except UserProfile.DoesNotExist:
            current_user_profile = None

        walks = Walk.objects.filter(user=current_user_profile.user).order_by('-date_published')

        if current_user_profile == None:
            context_dict = {}
            context_dict['username'] = 'None type user'
        
        else:
            context_dict = {}

            if current_user_profile.is_moderator:
                context_dict['username'] = current_user_profile.user.username + ' (moderator)'
            else:
                context_dict['username'] = current_user_profile.user.username

            context_dict['email'] = current_user_profile.user.email
            context_dict['date_of_birth'] = current_user_profile.date_of_birth
            context_dict['profile_picture'] = current_user_profile.profile_picture 
            context_dict['total_likes'] = current_user_profile.total_likes 
            context_dict['total_views'] = current_user_profile.total_views 

            if len(walks) != 0:
                context_dict['walks'] = walks
            else:
                context_dict['walks'] = None
            
    return render(request, 'stroll/my_profile.html', context=context_dict)

def edit_profile(request):
    context_dict = {}

    try:
        current_user_profile = UserProfile.objects.get(user=request.user)
        context_dict['user_profile'] = current_user_profile

    except (UserProfile.DoesNotExist, TypeError):
        return HttpResponse("Access Denied")
    
    
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        date_of_birth = request.POST.get('date_of_birth')
        profile_picture = request.POST.get('profile_picture') 

        if username:
            current_user_profile.user.username = username

        if email:
            current_user_profile.user.email = email

        if date_of_birth:
            current_user_profile.date_of_birth = date_of_birth

        if profile_picture:
            current_user_profile.profile_picture = request.FILES['profile_picture']

        current_user_profile.user.save()
        current_user_profile.save()

        return redirect(reverse('stroll:my_profile'))


    return render(request, 'stroll/edit_profile.html', context=context_dict)

def my_walks(request):
    context_dict = {}
    user = request.user
    if not user.is_authenticated:
        return redirect(reverse('stroll:login'))
    
    def toInt(string):
        if string != "":
            return int(string)
        else:
            return string

    context_dict = {}
    context_dict["walks"] = Walk.objects.filter(user=user)

    form = SearchWalkForm()
    if request.method == 'POST':
        title = area = description = tags = min_length = max_length = min_difficulty = max_difficulty = search = ""
        level = request.POST['form-level']

        if level == 'advanced':
            title = request.POST['title']
            area = request.POST['area']
            description = request.POST['description']
            tags = request.POST['tags']

            min_length = toInt(request.POST['min_length'])
            max_length = toInt(request.POST['max_length'])
            min_difficulty = toInt(request.POST['min_difficulty'])
            max_difficulty = toInt(request.POST['max_difficulty'])

            kwargdict = {'title__icontains': title,
                    'area__icontains': area,
                    'description__icontains': description,
                    'tags__icontains': tags,}
            if min_length:
                kwargdict['length__gte'] = min_length*1000
            if max_length:
                kwargdict['length__lte'] = max_length*1000
            
            if min_difficulty:
                kwargdict['difficulty__gte'] = min_difficulty

            if max_difficulty:
                kwargdict['difficulty__lte'] = max_difficulty

            context_dict["walks"] = Walk.objects.filter(**kwargdict, user=user)


    context_dict['form'] = form
    return render(request, 'stroll/my_walks.html', context=context_dict)

def my_questions(request):
    user = request.user
    if not user.is_authenticated:
        return redirect(reverse('stroll:login'))
    
    ordering = 'likes'

    if request.method == 'GET':
        ordering = request.GET.get('ordering')

        if ordering not in ['likes', 'views', 'date_published']:
            ordering = 'likes'

    context_dict = {}
    user_profile = UserProfile.objects.get(user=request.user)

    context_dict['questions'] = Question.objects.filter(user=user_profile).order_by('-'+ordering)
    return render(request, 'stroll/my_questions.html', context=context_dict)

def search_walks(request):

    def toInt(string):
        if string != "":
            return int(string)
        else:
            return string

    context_dict = {}
    context_dict["search_results"] = Walk.objects.all()

    form = SearchWalkForm()
    if request.method == 'POST':
        title = area = description = tags = min_length = max_length = min_difficulty = max_difficulty = search = ""
        level = request.POST['form-level']

        if level == 'simple':
            search = request.POST['search']
            
            context_dict["search_results"] = (Walk.objects.filter(title__icontains=search) |
                                              Walk.objects.filter(area__icontains=search) |
                                              Walk.objects.filter(description__icontains=search) |
                                              Walk.objects.filter(tags__icontains=search))


        elif level == 'advanced':
            title = request.POST['title']
            area = request.POST['area']
            description = request.POST['description']
            tags = request.POST['tags']

            min_length = toInt(request.POST['min_length'])
            max_length = toInt(request.POST['max_length'])
            min_difficulty = toInt(request.POST['min_difficulty'])
            max_difficulty = toInt(request.POST['max_difficulty'])

            kwargdict = {'title__icontains': title,
                    'area__icontains': area,
                    'description__icontains': description,
                    'tags__icontains': tags,}
            if min_length:

templates/stroll/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load stroll_template_tags %}

<html>
    <head lang="en">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
      <link rel="stylesheet" type="text/css" href="{% static 'css/base_style.css' %}">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
      <script src="{% static 'js/stroll-ajax.js' %}"></script>
      {% block stylesheet_block %}
      {% endblock %}
      {% block script_block %}
      {% endblock %}

      <link rel="stylesheet" type="text/css" href="{% static 'css/map.css' %}">

      <meta charset="UTF-8" />
      <title>
          Stroll - 
          {% block title_block %}
              All Things Walking
          {% endblock %}
      </title>
      <link rel="icon" type="image/x-icon" href="{% static 'images/stroll_icon.png' %}">
    </head>
    <body>
        <div class="background">
        <!-- This code is a modified version of the bootstrap template for the nav bar -->
        <nav class="navbar navbar-expand-md header">
            <div class="container-xxl">
                <a href="{% url 'stroll:home' %}"><img src="{% static 'images/stroll_logo.png' %}" width="96" height="56"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <form class="d-flex ms-auto" id="search_form" method="post" action="{% url 'stroll:search_walks' %}" >
                  {% csrf_token %}
                  <input class="form-control me-2" type="search" name="search" placeholder="Search walks" aria-label="Search">
                  <input type="hidden" name="form-level" value="simple" />
                  <input class="btn header_button" type="submit" value="Search" >
                </form>
                <ul class="navbar-nav ms-auto mb-lg-0">
                  {% if request.user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link header_text" href="{% url 'stroll:create_walk' %}">Create Walk</a>
                  </li>
                  {% else %}
                  <li class="nav-item">
                    <a class="nav-link header_text" href="{% url 'stroll:login' %}">Create Walk</a>
                  </li>
                  {% endif %}
                  {% if request.user.is_authenticated %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle header_text" href="{% url 'stroll:create_walk' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        My Account/Signout
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'stroll:my_profile' %}">My Account</a></li>
                      <li><a class="dropdown-item" href="{% url 'stroll:logout' %}">Signout</a></li>
                    </ul>
                  </li>
                  {% else %}
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle header_text" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Login/Signup
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'stroll:login' %}">Login</a></li>
                      <li><a class="dropdown-item" href="{% url 'stroll:signup' %}">Signup</a></li>
                    </ul>
                  </li>
                  {% endif %}
                
              </div>
            </div>
          </nav>

        <div class="container p-5">
            {% block body_block %}
            {% endblock %}
        </div>
    </div>
    <!-- Footer code inspired from the bootstrap website -->
        <footer class="footer">
          <navbar class="navbar navbar-expand-lg">
          <div class="container-xxl justify-content-center">
            <div class="row py-3">
              <div class="col-lg col-12 text-center">
                <a href="{% url 'stroll:home' %}">
                  <img src="{% static 'images/stroll_logo.png' %}" width="192" height="111.75">
                </a>
              </div>
              
              <!-- Displays your most recently viewed walks -->
              {% for walk in request.COOKIES.recently_viewed_walks|get_walks_from_cookie %}
                  {% if walk %}
                    <div class="col-lg-2 col-0 d-none d-lg-block footer_walk_container">
                      <!-- Brings in the HTML required for a walk element in icon form -->
                      {% walk_element walk display_type="small" %}
                    </div>
                  {% endif %}
              {% endfor %}

              <div class="col-lg col-12 text-center">
                  <div class="row fluid footer_text"><a href="{% url 'stroll:home' %}">Home</a></div>
                  <div class="row"><a href="{% url 'stroll:about' %}">About Us</a></div>
                  <div class="row"><a href="{% url 'stroll:questions' %}">Question Forum</a></div>
              </div>
            </div>
          </div>
          </navbar>
        </footer>
    </body>
</html>

templates/stroll/comments_section.html
<!DOCTYPE html>
{% load staticfiles %}
{% load stroll_template_tags %}
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'css/comments_section.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/form_style.css' %}"/>
    </head>
    <body>
        <div class="container-xxl main_body">
            <div class="row screen comment_section">
                <div class="col content_seperator">
                    <div class="row section_text">
                        <h4>Comments</h4>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="row">
                            {% if parent == "question" %}
                                <form class="content_seperator" id="question_form" method="post" action="{% url 'stroll:show_question' id %}" >
                            {% elif parent == "walk" %}
                                <form class="content_seperator" id="walk_form" method="post" action="{% url 'stroll:show_walk' id %}" >
                            {% endif %}

                                {% csrf_token %}
                                <div class="col-12">
                                    <input class="form-control" type="text" name="comment" placeholder="Post Comment" aria-label="Post">
                                </div>
                                <div class="col-12">
                                    <input class="form-control submit_button" type="submit" name="submit" value="Post" />
                                </div>
                            </form>
                        </div>
                    {% else %}
                        <div class="row section_text">
                            <a href="{% url 'stroll:login' %}"><p>Log in to be able to post comments</p></a>
                        </div>
                    {% endif %}
                    <div class="row">
                        {% if comments|length == 0 %}
                            <p class="section_text">No one has left a comment yet. Be the first to comment!</p>
                        {% else %}
                            {% for comment in comments %}
                                <p>{% comment_element comment user parent %}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

templates/stroll/edit_profile.html
{% extends 'stroll/base.html' %}
{% load staticfiles %}

{% block stylesheet_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/form_style.css' %}"/>
{% endblock %}

{% block title_block %}
    Edit Profile
{% endblock %}

{% block body_block %}
<div class="container">
    <h1 class="title">Edit Profile</h1>
</div>
<div class="container-xxl content_box_thin main_body">
    <div>
        <form id="login_form" method="post" action="{% url 'stroll:edit_profile' %}">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <div class="row">
                        <div class="col form_box">
                                <strong>Leave Fields Blank for them to not be updated</strong>
                                <br />
                                Username: <input class="form-control" type="text" name="username" placeholder="{{ user.username }}" size="50" />
                                <br />
                                Email: <input class="form-control" type="text" name="email" placeholder="{{ user.email }}" size="50" />
                                <br />
                                Date Of Birth: <input class="form-control" type="date" name="date_of_birth" />
                                <br />
                                Profile Picture: <input class="form-control" type="file" accept="image/*" name="profile_picture" />
                                <br />
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col d-grid">
                    <input type="submit" class="btn submit_button" value="Login" />
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/stroll/home.html
{% extends 'stroll/base.html' %}
{% load staticfiles %}
{% load stroll_template_tags %}

{% block title_block %}
    Homepage
{% endblock %}

{% block stylesheet_block %}
{% endblock %}

{% block body_block %}
    <div class="container">
        <h1 class="title">Home - Popular Walks</h1>
    </div>
    <div class="container main_body">
    {% for walk in popular_walks %}
        <div class="row walk_tile">
            <div class="col">
                <!-- Brings in the HTML required for a walk element -->
                {% walk_element walk display_type="full" %}
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/stroll/login.html
{% extends 'stroll/base.html' %}
{% load staticfiles %}

{% block stylesheet_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/form_style.css' %}"/>
{% endblock %}

{% block title_block %}
    Log In
{% endblock %}

{% block body_block %}
<div class="container title">
    <h1>Log In</h1>
</div>
<div class="container-xxl content_box_thin main_body">
    <div>
        <form id="login_form" method="post" action="{% url 'stroll:login' %}">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <div class="row">
                        <div class="col form_box">
                                {{ errors }}
                                <br>
                                Username: <input class="form-control" type="text" name="username" value="" size="50" />
                                <br />
                                Password: <input class="form-control" type="password" name="password" value="" size="50" />
                                <br />
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col d-grid">
                    <input type="submit" class="btn submit_button" value="Login" />
                </div>
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col underbox_text">
        <a href="{% url 'stroll:signup' %}"><p>Don't have an account? Signup here</p>
    </div>
</div>
{% endblock %}

templates/stroll/my_profile.html
{% extends 'stroll/base.html' %}
{% load staticfiles %}
{% load stroll_template_tags %}


{% block stylesheet_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/my_profile.css' %}"/>
{% endblock %}

{% block title_block %}
    My Profile
{% endblock %}

{% block body_block %}
<div class="container">
    <h1 class="title">My Profile</h1>
</div>
<div class="container-xxl main_body">
    <div class="row content_seperator">
        <div class="col-lg-3 col-12 profile_card">
            <div class="row profile_column_text">
                <div class="col-lg-12 col-12 profile_photo_position">
                    <img src="{{ MEDIA_URL }}{{ profile_picture }}" class="profile_photo">
                </div>
                <div class="col-lg-12 col-6">
                    <h4>Likes: {{ total_likes }}</h4>
                </div>
                <div class="col-lg-12 col-6">
                    <h4>Views: {{ total_views }}</h4>
                </div>
                <div class="col-lg-12 col-6">
                    <a href="{% url 'stroll:my_walks' %}"><h4>My Walks</h4></a>
                </div>
                <div class="col-lg-12 col-6">
                    <a href="{% url 'stroll:my_questions' %}"><h4>My Questions</h4></a>
                </div>
                <div class="col-lg-12 col">
                    <a href="{% url 'stroll:logout' %}"><h4>Signout</h4></a>
                </div>
            </div>
            
        </div>
        <div class="col-lg-6 col-12">
            <div class="row details_position details_text">
                <div class="col-12">
                    <h4>Username: {{ username }}</h4>
                </div>
                <div class="col-12">
                    <h4>Email: {{ email }}</h4>
                </div>
                <div class="col-12">
                    {% if date_of_birth %}
                        <h4>Date of Birth: {{ date_of_birth }}</h4>
                    {% else %}
                        <h4>Date of Birth: no date of birth registered</h4>
                    {% endif %}
                </div>
                <div class="col-12">
                    <h4><a href="{% url 'stroll:edit_profile' %}">Edit Profile</a></h4>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-12 profile_card">
            <div class="row main_body">
                <h4 class="title">
                    {% if walks %}
                        My Recent Walks:
                    {% else %}
                        No Recent Walks
                    {% endif %}
                </h4>
            </div>
            <div class="row">
                {% if walks %}
                    {% for walk in walks %}
                        <div>
                            <p class="row walk_position">{% walk_element walk display_type="small" %}</p>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}